# Generated by Django 5.1.7 on 2025-03-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Введите ваше имя.",
                max_length=128,
                unique=True,
                verbose_name="Имя сотрудника",
            ),
        ),
    ]
