# Generated by Django 5.1.7 on 2025-03-30 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="название электроники"
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=128, verbose_name="модель электроники"),
                ),
                (
                    "date_release",
                    models.DateField(verbose_name="дата выхода продукта на рынок"),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="ElectronicsRetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_level_retail",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Уровень иерархии сети"
                    ),
                ),
                (
                    "level_name_retail",
                    models.CharField(
                        choices=[
                            ("Завод", "Завод"),
                            ("Розничная сеть", "Розничная сеть"),
                            (
                                "Индивидуальный предприниматель",
                                "Индивидуальный предприниматель",
                            ),
                        ],
                        max_length=30,
                        verbose_name="юридический статус сети",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="e-mail компании"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="страна")),
                ("city", models.CharField(max_length=100, verbose_name="город")),
                ("street", models.CharField(max_length=100, verbose_name="улица")),
                (
                    "house_number",
                    models.CharField(max_length=10, verbose_name="номер дома"),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=16,
                        verbose_name="задолженность перед поставщиком",
                    ),
                ),
                (
                    "date_time_born",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="electronics_retail.electronicsretail",
                        verbose_name="поставщик",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="electronics_retail",
                        to="electronics_retail.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сеть продажи электроники",
                "verbose_name_plural": "Сети продажи электроники",
            },
        ),
    ]
